### ISSUE TITLE
-

### ISSUE THREAD

**Issue by jtd-n** [ITDZK/api#6]

**Comment by oct1k** [comment]
Доброго дня, хочу поцікавитись чи знайшли Ви відповідь на своє питання?
Мене ця тема також зацікавила і хотів би отримати список API заявок.

**Comment by JourneyToDev** [comment]
> Доброго дня, хочу поцікавитись чи знайшли Ви відповідь на своє питання? Мене ця тема також зацікавила і хотів би отримати список API заявок.

Доброго времени. К сожалению разработчики так и не ответили, а другой информации найти не получилось. Есть вероятность, что такие запросы в API просто не были реализованы. Как альтернативное решение для автоматизации получения нужной информации можно использовать Selenium (например в связке или отдельно с headless webdriver), но это не так удобно и потребует дополнительных затрат времени на написание кода и файловых зависимостей. Во всяком случае, за неимением лучшего, этот способ сейчас частично используем. Oct1k, если Вам вдруг встретится более оптимальное решение то пожалуйста сообщите.
